### ISSUE TITLE
Artifact of Metamorphosis breaks character loading

### ISSUE THREAD

**Issue by QuentinMcCarthy** [TeamMoonstorm/Starstorm2#232] opened 2023-04-05 08:32 UTC
Installed Startstorm 2 into my modlist because I thought it'd be neat and a lot of mods mention Typhoon difficulty. New survivors, new items, what's not to enjoy?

For starters, Nemesis Commando was unlocked before I'd even played the game. I assumed that was because I'd already fulfilled the requirements, but I don't even know what the requirements are, so I'm not sure.

The biggest issue I faced, however, was game-breaking. I play using the Artifact of Metamorphosis because I enjoy the randomness. Having Starstorm 2 enabled in my modlist breaks the Artifact and causes characters to fail to spawn entirely. I tried to force a spawn using Aerolt but even that reports an error that the character could not be spawned. Disabling Starstorm fixes the issue.

It's possible it's an incompatability issue as I have 75 other mods that I play with (a good portion frameworks and dependencies such as R2API).

The error that is reported in the console upon attempting to spawn in-game is thus:
```
[Error  : Unity Log] ArgumentNullException: Value cannot be null.
Parameter name: entitlementDef
Stack trace:
RoR2.EntitlementManagement.BaseUserEntitlementTracker`1[TUser].UserHasEntitlement (TUser user, RoR2.EntitlementManagement.EntitlementDef entitlementDef) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0008)
RoR2.SurvivorDef.CheckRequiredExpansionEnabled (RoR2.NetworkUser networkUser) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0028)
RoR2.CharacterMaster+<>c__DisplayClass162_0.<PickRandomSurvivorBodyPrefab>g__SurvivorIsUnlockedAndAvailable|0 (RoR2.SurvivorDef survivorDef) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0010)
System.Linq.Enumerable+WhereArrayIterator`1[TSource].MoveNext () (at <55b3683038794c198a24e8a1362bfc61>:IL_002B)
System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) (at <55b3683038794c198a24e8a1362bfc61>:IL_0072)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <55b3683038794c198a24e8a1362bfc61>:IL_000E)
RoR2.CharacterMaster.PickRandomSurvivorBodyPrefab (Xoroshiro128Plus rng, RoR2.NetworkUser networkUser, System.Boolean allowHidden) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_002A)
RoR2.CharacterMaster.Respawn (UnityEngine.Vector3 footPosition, UnityEngine.Quaternion rotation) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_005B)
RoR2.Stage.RespawnCharacter (RoR2.CharacterMaster characterMaster) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0047)
RoR2.CharacterMaster.CmdRespawn (System.String bodyName) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0050)
RoR2.CharacterMaster.CallCmdRespawn (System.String bodyName) (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0021)
RoR2.Stage.RespawnLocalPlayers () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0060)
RoR2.Stage.Start () (at <abee4f3b46184662b4d0bd0bc9965114>:IL_0050)
```

**Comment by Zenithrium** [comment] 2023-04-08 03:47
known issue, duplicate of #151. We're working on it

**Closed by Zenithrium** 2023-04-08 03:47 UTC
