### ISSUE TITLE
Coffeebag in the hands of enemies gives

### ISSUE THREAD

**Issue by rampagerock** [TeamMoonstorm/Starstorm2#209] opened 2023-01-22 12:49 UTC
When playing with the Evolution artefact, enemies get an item per stage.
When they get a **coffeebag**, the player (singleplayer) gets the coffeebag buff X amount of times, at the same time, where X is amount of enemies (I think), every time an interactable is used.
Only noticed because with every interactable I had frame-drops.

![image](https://user-images.githubusercontent.com/10922682/213916610-0883b860-b31d-4e17-9aa6-aa0f6cc8e9f1.png)
(the buff number/timer/amount also switch around, as if overflowing into eachother)

[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/10474441/LogOutput.log)

**Comment by rampagerock** [comment] 2023-02-16 18:27
This is apparently not the first time this issue popped up.
I only looked through the active issues, and not previous/closed issues
-> https://github.com/TeamMoonstorm/Starstorm2/issues/148
Something popped back

**Comment by Zenithrium** [comment] 2023-02-16 18:52
no, i'm pretty sure these are different issues entirely - they both do relate to enemies getting the item, but the first one was because every time an enemy spawned it was given 30 stacks of a buff (which takes a little bit of time) whereas this issue is caused by me not checking if the entity that interacted with something actually has coffee bag, and it proccing for every single entity that currently has the item

**Comment by prodzpod** [comment] 2023-03-31 20:26
zenith >:// (will be fixed in april release)

**Comment by Zenithrium** [comment] 2023-04-01 01:06
hey! i've never broken anything!
i think i already committed a fix for this?

**Comment by prodzpod** [comment] 2023-04-01 04:12
so this one is pushed, huh....

**Closed** 2023-04-24 00:54 UTC
Labels: Bug, Fixed In Next Update
