### ISSUE TITLE
Empyrean enemy spawn freezes game

### ISSUE THREAD

**Issue by JoeMoMo499** [TeamMoonstorm/Starstorm2#489] opened 2024-08-01 04:05 UTC
I'm not really sure how to get a crash report for this, as the game is frozen and has been for more than 5 minutes, but there is no crash log. This has happened twice now when I have reached Empyrean (stage 9) on typhoon, with Kin, Swarms, Honor, Sacrifice, and Command on. 

I cannot attach the LogOutput file as it is too large for GitHub. I will attempt to attach in 2 parts. 

I have truncated the LogOutput file. It was falsely enlarged by an incredibly number of rows that just said 
[Info   : Unity Log] HermitCrabBody : CHOSEN MONSTER ATTEMPT
and I have left the first log of this in the report. 
[LogOutput - Copy.log](https://github.com/user-attachments/files/16450069/LogOutput.-.Copy.log)

**Comment by nayDPz** [comment] 2024-08-01 04:17
This is a known issue and will be fixed in 0.7. 

The freeze is caused by the Empyrean event failing to find a monster that isn't in its blacklist. This can happen when Kin selects a monster that IS in the blacklist, or with certain family events.

**Comment by JoeMoMo499** [comment] 2024-08-01 04:19
Ah, that makes sense. 

Thank you very much for the fast response!

**Closed** 2024-08-01 04:19 UTC
