### ISSUE TITLE
Nemesis Commando distant gash doesn't do gouging damage

### ISSUE THREAD

**Issue by BrackChunky** [TeamMoonstorm/Starstorm2#228] opened 2023-03-27 19:32 UTC
When I play Nemesis Commando and use his distant gash move I notice that it doesn't do gouging damage like his M1 and Special moves do, even though it says it will in the move description. Im going to assume that this is a bug of the mod currently.

**Comment by Zenithrium** [comment] 2023-03-28 20:28
duplicate of #196

**Closed by Zenithrium** 2023-03-28 20:28 UTC
