### ISSUE TITLE
Potential Conflict / Unknown Issue

### ISSUE THREAD

**Issue by WESGaming5** [TeamMoonstorm/Starstorm2#651] opened 2024-12-01 01:03 UTC
RoR2 boots successfully, and a new run can even be started. However, a few notable, consistent errors occur:
-My survivor spawns as though teleporting from a prior stage, and a moment later the drop pod falls on my position.
-The teleporter fails to spawn; this is fixed by returning to menu and starting a second run, but reoccurs if I restart the game.
-Enemies are all of the same type, even with no artifacts enabled.
-If the enemies are elites, all enemies are elites and are furthermore elites of the same type.

A bit of further context that may be relevant:
-I have a lot of mods installed (100+); I would rather not try removing mods and messing up my logbook / stats to find the particular conflict if possible, but can do so if the log file is inconclusive. I can also provide a list of all installed mods.
-I install mods manually rather than via a mod manager, and am strongly disinclined to use a mod manager; if that's a hard prerequisite for Starstorm2, I understand, though I think that should be better communicated.
-I removed my steam name and profile name from the log file; I replaced them with _STEAMNAME_ and _PROFILENAME_ respectively, though I can't fathom this having any effect on potentially deciphering the problem from the log file.

[LogOutput - Copy.log](https://github.com/user-attachments/files/17967479/LogOutput.-.Copy.log)

**Comment by Hevia** [comment] 2024-12-01 09:50
Hey @WESGaming5 ! 

Thanks for filing the issue. Sadly we do not support issues filed via manual mod installs. The issue is that there are just wayyyy too many things that can go wrong with a manual install, we could spend all day trying to repo it, and often when we're looking to repo a mod compat bug, we require folks give us a profile code so we can have the same mod lists + mod versions and try ourselves

I did look at your log regardless. Some suggestions though:
- You can always build r2modman from source yourself (thats the non adware/overwolf version)
- I dont see any error from SS2 that describes the issue youre having. Many of the SS2 related errors are harmless
- Hmm this might be an error on our end, but it says youre using SS2 0.6.10, and the latest is 0.6.14. Although you could be on the latest and we forgot to update the versioning in the dll. I havent checked
- I did notice some item mods that I believe are broken, like: hex3 + mystics items, make sure youre using the fixed versions of those mods uploaded by other folks after SOTS. This goes for every mod present
- The benefit of a mod manager is you can very easily disable mods in chunks to see whats causing your issue
- TinkersSatchel or any mod that requires TILER is just not worth having. Tiler is the cause of a lot of bugs and odd behavior. I dont believe anyone has released a replacement yet either. Just not worth having imo

Sorry this is not a direct fix! We will be closing as for the reason stated earlier. Good luck, I hope something here provides a lead + solution

**Closed by Hevia** 2024-12-01 09:50 UTC
