### ISSUE TITLE
Crashing After Open Cutscene, Can't use mod after 4.4

### ISSUE THREAD

**Issue by risenS** [TeamMoonstorm/Starstorm2#275] opened 2023-06-03 20:17 UTC
Game will crash after the opening cutscene.  I use quite a few mods and had to look at the console and saw that this mod was throwing a lot of errors.  When I disabled this mod I could play as normal.  I hope you guys get the issue resolved because I like the extra items this mod integrates.

**Comment by swuff-star** [comment] 2023-06-05 18:11
Would you care to share a log with the details of this crash? We've also recently put out update 0.4.5, which fixed a major crash caused by an incompatibility with other mods - it would be greatly appreciated if you could attempt to reproduce the error on this new version, and provide a log should it still recur.

**Comment by Nebby1999** [comment] 2023-06-12 17:00
I'm closing this as completed for now, reopen if crash persists

**Closed** 2023-06-12 17:00 UTC
