### ISSUE TITLE
Executioner new secondary

### ISSUE THREAD

**Issue by Jlouck20** [TeamMoonstorm/Starstorm2#358] opened 2023-11-03 15:09 UTC
When using the new lamp boss item on executioner, holding down both the secondary skill button and the primary skill button at the same time will fire the spirit bolts in rapid succession, rather than after every fifth primary shot. Unsure if this is due to overcoming an attack speed threshold, or if it does this naturally.

**Comment by Zenithrium** [comment] 2023-11-05 21:25
Duplicate of #350

**Closed by Zenithrium** 2023-11-05 21:25 UTC
