### ISSUE TITLE
Nemesis Commando invasion in planetarium doesn't spawn Nemmando.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [TeamMoonstorm/Starstorm2#271] opened 2023-06-01 20:49 UTC
Was doing a run with some pals, got through to the end and fought voidling and got the pop up text for him spawning. We checked all 3 sections of the planetarium stage but he never spawned. Bigger question is, is it normal for Nemmando to attempt to spawn in Planetarium?

Don't have the log i'm afraid, nor know a reliable way to force the nemmando spawn so I can't really test this myself to verify if this was just a one time bug.

**Comment by swuff-star** [comment] 2023-06-01 21:26
his spawn card currently doesn't list planetarium as a set stage, which does indeed make this odd - would you happen to have a log of the run? will look into

**Comment by Nebby1999** [comment] 2023-06-02 03:24
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/11631574/LogOutput.log)
Can confirm he spawns on planetarium, for whatever reason.

not an interop issue, as this was basically with just ss2 installed

**Comment by Nebby1999** [comment] 2023-06-02 16:07
Fixed on DirectorAPI's 1.1.1 update, this was caused by an upstream issue. more info can be found on the pull request that mentioned this issue.

**Closed by Nebby1999** 2023-06-02 16:07 UTC
