### ISSUE TITLE
vagrant penis very large and bright on nemmando

### ISSUE THREAD

**Issue by penith** [TeamMoonstorm/Starstorm2#92] opened 2022-10-17 10:45 UTC
![image](https://user-images.githubusercontent.com/93685790/196158268-12b6edf8-855c-47fd-aba2-54e739ab45dc.png)

**Comment by swuff-star** [comment] 2022-10-17 14:11
duplicate of #90 but with better phrasing. acknowledged 👍

**Closed by swuff-star** 2022-10-17 14:11 UTC
