### ISSUE TITLE
cant pick up items BUG

### ISSUE THREAD

**Issue by eyalHANDASAIM** [TeamMoonstorm/Starstorm2#14] opened 2022-06-25 22:12 UTC
when an item drops, doesnt matter how, it is impossible to pick it up.
BUT as long as you stand on the item the game gives you the stats but it doesnt show the item on the item list. 
Example, opened a chest that dropped a solider sarringe. stood on the item for a moment and than started to attack super fast, after dying it showed that i had over 500 coppies of it.

for some reason, if i start a new game without changing the diffucilty of it the bug doesnt happen. 

one more thing, menue text dissapears after starting a game (I dont know if it is related or a diffrent bug)
![image](https://user-images.githubusercontent.com/22292811/175791865-ecddf6fb-635e-44ae-ae97-490a3a2e2612.png)
![image](https://user-images.githubusercontent.com/22292811/175791891-b81a933d-83af-4caf-8b6f-ee9544162b34.png)

logs (I think this is the log folder. tell me if its the wrong folder, and if so were to find the true one)
[LogOutput.log](https://github.com/TeamMoonstorm/Starstorm2/files/8985640/LogOutput.log)

**Comment by eyalHANDASAIM** [comment] 2022-06-26 16:45
I tried to check some stuff:
![image](https://user-images.githubusercontent.com/22292811/175824860-c299cd2c-8740-47b1-b523-f77e2848b5ea.png)
![image](https://user-images.githubusercontent.com/22292811/175824867-a14f2e31-7fe4-42f5-8315-ca07456ff808.png)
 
 this is probably related to the bug, because with the bug the item stack stays forever on the ground

**Comment by eyalHANDASAIM** [comment] 2022-06-26 18:38
i did the following changes to some files in config and it fixed the problem. 
i dont know for sure which change fixed it, but its probably the unlock-all item one. 
![image](https://user-images.githubusercontent.com/22292811/175829177-8258a2c1-e9c1-4cbb-8e0a-797874448e1a.png)
![image](https://user-images.githubusercontent.com/22292811/175829183-39663e41-3d26-464e-9401-5952e4b8a82e.png)
![image](https://user-images.githubusercontent.com/22292811/175829186-3092eaca-aaf9-4f48-8ef6-039551e4c947.png)

**Comment by Nebby1999** [comment] 2022-07-04 19:25
This bug is caused by nkota's achievement, as such, the unlock and achievement of Nkota's heritage has been removed temporarely.

this will be fixed prior to 0.4.0's release

**Closed** 2022-08-13 06:54 UTC
Labels: Bug, Good First Issue
